### ISSUE TITLE
Case change

### ISSUE THREAD

**Issue by unbreaking-V** [ivysochyn/textiv#10]
### Description:
As a user I can change the case of letters - set of three transformations (upper, lower, capitalize)
#### 1. Changing the case of letters - set of three transformations (upper, lower, capitalize)

- upper - all letters capitalized: `upper -> UPPER `.
- lower - all letters to lower case: ` lower -> lower `.
- capitalize - first letter in each word to uppercase: ` capitalize text -> Capitalize Text`.

### Parallel tasks:

1. Writing function documentation (javadoc)
2. Creating unit tests

**Comment by ivysochyn** [comment]
Changes were merged to main.
