### ISSUE TITLE
Number to words 

### ISSUE THREAD

**Issue by unbreaking-V** [ivysochyn/textiv#11]
### Description:
As a user I can convert numbers into text in English. 
### Acceptance criteria:

- conversion of integers up to 1000
- conversion of floating point numbers to hundredths

### Example:
`Deposit 100 zloty -> deposit one hundred zloty`

### Parallel tasks:

1.  Writing function documentation (javadoc)
2.  Creating unit tests

**Comment by unbreaking-V** [comment]
1. Add a function to pull a number out of a string 
2. Add a function to replace a number with a word

**Comment by ivysochyn** [comment]
Changes were merged to main.
