### ISSUE TITLE
Expanding/collapsing abbreviations

### ISSUE THREAD

**Issue by unbreaking-V** [ivysochyn/textiv#12]
### Description:
As a user I can o convert selected (predefined) words into shortcuts. 

### Acceptance criteria:

- Abbreviation expansion: `for example -> e.g.`.
- Abbreviation expansion: `among others -> m.in.`.
- Abbreviation expansion: `and the like -> etc.`.
- Works **size-independent**.

### Parallel tasks:

1. Writing function documentation (javadoc)
2. Creating unit tests

**Comment by ivysochyn** [comment]
Expanded list of abbreviations, reviewed changes, and added tests.

Changes were merged to main branch.
