### ISSUE TITLE
String inversion 

### ISSUE THREAD

**Issue by unbreaking-V** [ivysochyn/textiv#16]
### Description:
As a user, I can invert a string with case-sensitive characters at specific positions (inverse).
### Acceptance criteria:

- Preservation of uppercase and lowercase positions: `MirEk -> KerIm`.
- String inversion
- Support for all characters **UTF-8**

### Parallel tasks:

1. Writing function documentation (javadoc)
2. Creating unit tests

**Comment by ivysochyn** [comment]
Changes were merged to main.
