### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by unbreaking-V** [ivysochyn/textiv#36]
### Add some missing unit tests to the function :

- EscapeCharactersTextTransformer

- InversionTextTransformer

### Add moke tests  to the function: 
 
- CreateTextTransformer

**Comment by ivysochyn** [comment]
Added 10 mock tests.

**Comment by ivysochyn** [comment]
Reviewed changes, added unit tests to the `TextTransformerCreator` and merged changes.
