### ISSUE TITLE
Fix typos 

### ISSUE THREAD

**Issue by unbreaking-V** [ivysochyn/textiv#7]
### Opis:
Jako użytkownik mogę wykryć i naprawić błędy w pisowni tekstu .
#### 1. Korekta błędów ortograficznych : 
- `acceept -> accept`
- `thier -> their`
- `untill -> until`
- `diffrent -> different`

**Comment by ivysochyn** [comment]
Added tests, documentation for typos fixing. Also performed a few fixes of warnings.

**Comment by ivysochyn** [comment]
@mikolajzaleski along with @Zajancz have to resolve the ones that left.
